#!/usr/bin/env groovy
// WARNING: Do not edit this file directly in your own repository.
// It is maintained in the grails-plugin-template repository.
// https://github.com/grails-plugins/grails-plugin-template/tree/main/.github/scripts
@Grab('org.apache.groovy:groovy-yaml')
import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import groovy.yaml.YamlBuilder
import groovy.yaml.YamlSlurper

def token = System.getenv('GITHUB_TOKEN')
def repo  = System.getenv('GITHUB_REPOSITORY')

if (!token) {
    println "GITHUB_TOKEN not set — skipping contributor update"
    System.exit(0)
}

def requestProps = [
    Authorization : "token ${token}",
    'User-Agent'  : 'update-contributors-action',
    Accept        : 'application/vnd.github+json',
]

// 1. Fetch all contributors via REST (sorted by contributions desc, bots excluded)
def contributors = []
def page = 1
while (true) {
    def url = "https://api.github.com/repos/${repo}/contributors?per_page=100&page=${page}"
    def batch = new JsonSlurper().parseText(url.toURL().getText(requestProperties: requestProps)) as List
    if (!batch) break
    contributors.addAll(batch)
    page++
}

def humans = contributors.findAll { it.type != 'Bot' }
if (!humans) {
    println "No human contributors found — skipping update"
    System.exit(0)
}

def nodeIds     = humans*.node_id
def loginByNode = humans.collectEntries { [it.node_id, it.login] }

// 2. Fetch display names via GraphQL
def gqlQuery = 'query($ids:[ID!]!){nodes(ids:$ids){...on User{id name login}}}'
def gqlBody  = JsonOutput.toJson([query: gqlQuery, variables: [ids: nodeIds]])

def conn = 'https://api.github.com/graphql'.toURL().openConnection() as HttpURLConnection
conn.doOutput = true
conn.requestMethod = 'POST'
conn.setRequestProperty('Authorization', "token ${token}")
conn.setRequestProperty('Content-Type', 'application/json')
conn.setRequestProperty('User-Agent', 'update-contributors-action')
conn.outputStream.withWriter { it << gqlBody }

def gqlNodes   = new JsonSlurper().parseText(conn.inputStream.text).data.nodes
def nameByNode = gqlNodes.findAll().collectEntries { [(it.id): (it.name ?: it.login)] } as Map<String, String>

// 3. Build ordered map: login → display name (preserving contribution order)
def ordered = humans.collectEntries { c ->
    def login = loginByNode[c.node_id]
    [login, nameByNode[c.node_id] ?: login]
} as LinkedHashMap<String, String>

// 4. Update the contributors section in project.yml
def projectYmlFile = new File('project.yml')
if (!projectYmlFile.exists()) {
    println "project.yml not found at repo root — cannot update contributors. " +
        "See TEMPLATE_README.md#projectyml."
    System.exit(1)
}
def projectYml = new YamlSlurper().parse(projectYmlFile) as Map

projectYml.contributors = ordered

def yaml = new YamlBuilder()
yaml(projectYml)
projectYmlFile.text = yaml.toString()

println "Updated ${ordered.size()} contributors in project.yml"
