#!/usr/bin/env groovy
// WARNING: Do not edit this file directly in your own repository.
// It is maintained in the grails-plugin-template repository.
// https://github.com/grails-plugins/grails-plugin-template/tree/main/.github/scripts
@Grab('org.apache.groovy:groovy-yaml')
import groovy.json.JsonSlurper
import groovy.yaml.YamlBuilder
import groovy.yaml.YamlSlurper

def token = System.getenv('GITHUB_TOKEN')
def repo  = System.getenv('GITHUB_REPOSITORY')

if (!token) {
    println "GITHUB_TOKEN not set — skipping version update"
    System.exit(0)
}

def requestProps = [
    Authorization: "token ${token}",
    'User-Agent' : 'update-versions-action',
    Accept       : 'application/vnd.github+json',
]

def projectYmlFile = new File('project.yml')
if (!projectYmlFile.exists()) {
    println "project.yml not found at repo root — cannot update versions or generate the gh-pages index. " +
        "See TEMPLATE_README.md#projectyml."
    System.exit(1)
}
def projectYml = new YamlSlurper().parse(projectYmlFile) as Map
def ignore     = (projectYml.versions?.ignore ?: []) as List<String>

def entries = []
try {
    entries = new JsonSlurper().parseText(
        "https://api.github.com/repos/${repo}/contents/?ref=gh-pages"
            .toURL().getText(requestProperties: requestProps)
    ) as List
} catch (FileNotFoundException ignored) {
    // No gh-pages branch yet (e.g. the plugin hasn't released for the first time,
    // or this is the template repo itself, which never publishes). Fall through
    // with no versioned directories rather than failing the workflow.
    println "No gh-pages branch found for ${repo} — building index with snapshot only"
}

def semver   = ~/^\d+\.\d+\.(\d+|x)(-.*)?$/
def parseVer = { String v ->
    def m = v =~ /^(\d+)\.(\d+)\.(x|\d+)(?:-(.+))?$/
    if (!m) return [0, 0, -2, '']
    [m[0][1] as int, m[0][2] as int, m[0][3] == 'x' ? -1 : m[0][3] as int, m[0][4] ?: '']
}

def sorted = entries
    .findAll { it.type == 'dir' && (it.name as String) ==~ semver }
    .collect { it.name as String }
    .findAll { v -> !ignore.contains(v) }
    .toSorted { a, b ->
        def av = parseVer(a)
        def bv = parseVer(b)
        bv[0] <=> av[0] ?: bv[1] <=> av[1] ?: bv[2] <=> av[2] ?:
            (!av[3] && bv[3] ? -1 : av[3] && !bv[3] ? 1 : bv[3] <=> av[3])
    }

def hasVersions = !sorted.isEmpty()

if (hasVersions) {
    // ignore is preserved; only current and previous are updated
    projectYml.versions.current  = sorted.first()
    projectYml.versions.previous = sorted

    def yaml = new YamlBuilder()
    yaml(projectYml)
    projectYmlFile.text = yaml.toString()

    println "Versions updated: current=${projectYml.versions.current}, total=${sorted.size()}"
} else {
    println "No versioned directories found on gh-pages — building index with snapshot only"
}

// Generate index.html so the workflow can push it directly to gh-pages
def tmplFile = new File('docs/src/docs/index.tmpl')
if (tmplFile.exists()) {
    def githubOrg     = projectYml.github.org as String
    def githubProject = projectYml.github.project as String
    def optionsHtml   = sorted
        .collect { v -> "<option value=\"${v}\">${v}</option>" }
        .join('\n                    ')

    def tokens = [
        HAS_VERSIONS          : hasVersions,
        LATEST_VERSION        : hasVersions ? projectYml.versions.current : '',
        OTHER_VERSIONS_OPTIONS: optionsHtml,
        GITHUB_REPO_URL       : "https://github.com/${githubOrg}/${githubProject}",
        GITHUB_ORG_URL        : "https://github.com/${githubOrg}",
        PROJECT_TITLE         : projectYml.project.title as String,
        PROJECT_DESCRIPTION   : projectYml.project.description as String,
        PROJECT_ORG           : projectYml.project.org as String,
        REPO_SLUG             : githubProject,
    ]

    def html = new groovy.text.SimpleTemplateEngine().createTemplate(tmplFile.text).make(tokens).toString()
    def outFile = new File('build/index.html')
    outFile.parentFile.mkdirs()
    outFile.text = html
    println "Generated build/index.html"
}
