import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

version = projectVersion
group "io.github.gpc"

apply plugin: 'java-library'
apply plugin: "org.apache.grails.gradle.grails-plugin"
apply plugin: 'org.apache.grails.gradle.grails-publish'
apply plugin: "org.apache.grails.gradle.grails-gsp"

ext {
    buildInstant = java.util.Optional.ofNullable(System.getenv("SOURCE_DATE_EPOCH"))
            .filter(s -> !s.isEmpty())
            .map(Long::parseLong)
            .map(Instant::ofEpochSecond)
            .orElseGet(Instant::now)
    formattedBuildDate = DateTimeFormatter.ISO_INSTANT.format(buildInstant)
    buildDate = (buildInstant as Instant).atZone(ZoneOffset.UTC) // for reproducible builds
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.grails.org/grails/restricted' }
    maven {
        url = 'https://repository.apache.org/content/groups/snapshots'
        content {
            includeVersionByRegex('org[.]apache[.](grails|groovy).*', '.*', '.*-SNAPSHOT')
        }
    }
}

dependencies {
    profile "org.apache.grails.profiles:plugin"
    developmentOnly "org.springframework.boot:spring-boot-devtools"
    // Spring Boot DevTools may cause performance slowdowns or compatibility issues on larger applications
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    console "org.apache.grails:grails-console"
    compileOnly 'org.apache.grails:grails-core'
    compileOnly "org.apache.grails:grails-logging"
    compileOnly "org.apache.grails:grails-services"
    compileOnly "org.apache.grails:grails-url-mappings"
    testImplementation "org.apache.grails:grails-testing-support-web"

    implementation 'jakarta.mail:jakarta.mail-api:2.1.3'
    api "com.icegreen:greenmail:2.1.8"
}

compileJava.options.release = 17

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

grailsPublish {
    githubSlug = 'gpc/greenmail'
    license {
        name = 'Apache-2.0'
    }
    title = 'GreenMail Plugin'
    desc = "This plugin allows to have a mock greenmail SMTP (and more) server running inside a Grails application during development and test. It provides a view on the messages that was captured during sending mail"
    developers = [
            ldaley        : "Luke Daley",
            sbglasius     : "Søren Berg Glasius",
            mjhugo        : "Mike Hugo",
            antonevane    : "Anton N",
            jeffscottbrown: "Jeff Scott Brown",
            graemerocher  : "Graeme Rocher",
            yohannrub     : "Yohann Rubinsztejn",
            ZacharyKlein  : "Zachary Klein",
            ragufronz     : "ragufronz",
            kwongpan      : "Anthony",
            bkoehm        : "Brian Koehmstedt",
            zyro23        : "zyro",
            alvarosanchez : "Álvaro Sánchez-Mariscal",
            'ivo-k'       : "Ivo K",
    ]

}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

apply from: layout.projectDirectory.file('gradle/docs-config.gradle')
apply from: layout.projectDirectory.file('gradle/post-publish.gradle')
