projectVersion=8.0.0-RC1
# Maven group for the root project and all published subprojects
projectGroup=io.github.gpc
grailsVersion=8.0.0-M5
# Comma-separated list of projects to publish
projectsToPublish=greenmail
# Build dependencies
checkstyleVersion=10.21.4
codenarcVersion=3.6.0
jacocoVersion=0.8.12
asciidoctorVersion=4.0.5
testLoggerVersion=4.0.0
# Enable and set agree=yes to publish build scans from GitHub workflows
ciBuildScanPublish=true
ciBuildScanTermsOfUseUrl=https://gradle.com/terms-of-service
ciBuildScanTermsOfUseAgree=yes

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
