plugins {
    id 'config.code-coverage'
    id 'config.code-style'
    id 'config.compile'
    id 'config.grails-plugin'
    id 'config.project-metadata'
    id 'config.publish'
    id 'config.testing'
    id 'org.apache.grails.gradle.grails-gsp'
}

version = projectVersion
group = 'io.github.gpc'

dependencies {
    profile 'org.apache.grails.profiles:web-plugin'
    console 'org.apache.grails:grails-console'

    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-dependencies-starter-web'

    implementation 'jakarta.mail:jakarta.mail-api:2.1.5'

    // Public API: grails.plugin.greenmail.GreenMail extends com.icegreen.greenmail.util.GreenMail
    api 'com.icegreen:greenmail:2.1.12'

    testImplementation platform("org.apache.grails:grails-bom:$grailsVersion")
    testImplementation 'org.apache.grails:grails-dependencies-starter-web'
    testImplementation 'org.apache.grails:grails-dependencies-test'
}
