plugins {
    id 'groovy-gradle-plugin'
}

file('../gradle.properties').withInputStream {
    def gradleProperties = new Properties()
    gradleProperties.load(it)
    gradleProperties.each { k, v -> ext.set(k, v) }

}

repositories {
    maven { url = 'https://repo.grails.org/grails/restricted' }
    maven {
        url = 'https://repository.apache.org/content/groups/snapshots'
        content {
            includeVersionByRegex('org[.]apache[.](grails|groovy).*', '.*', '.*-SNAPSHOT')
        }
    }
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    implementation "org.asciidoctor.jvm.convert:org.asciidoctor.jvm.convert.gradle.plugin:$asciidoctorGradlePluginVersion"
    implementation 'org.apache.grails:grails-gradle-plugins'
    implementation 'cloud.wondrify:asset-pipeline-gradle'

}