import org.asciidoctor.gradle.jvm.AsciidoctorTask

plugins {
    id 'org.asciidoctor.jvm.convert'
    id 'config.project-metadata'
}

version = projectVersion
group = projectGroup

def asciidoctorAttributes = [
        'source-highlighter': 'coderay',
        toc                 : 'left',
        toclevels           : '2',
        'toc-title'         : 'Table of Contents',
        icons               : 'font',
        id                  : "${project.name - '-docs'}:${project.version}",
        idprefix            : '',
        idseparator         : '-',
        version             : project.version,
        projectUrl          : "https://github.com/${githubOrg}/${githubProject}",
        sourcedir           : "${rootProject.allprojects.find { it.name == 'greenmail' }.projectDir}/src/main/groovy",
        grailsVersion       : grailsVersion
]

tasks.named('asciidoctor', AsciidoctorTask) {

    outputDir = project.layout.buildDirectory.dir('docs')
    sourceDir = project.layout.projectDirectory.dir('src/docs')

    attributes(asciidoctorAttributes)
    baseDirFollowsSourceDir()
    options(doctype: 'book')
    sources { include 'index.adoc' }

    jvm {
        jvmArgs(
                '--add-opens', 'java.base/java.io=ALL-UNNAMED',
                '--add-opens', 'java.base/sun.nio.ch=ALL-UNNAMED'
        )
    }
}

static String resolveGrailsDocsDirName(String version) {
    version.endsWith('-SNAPSHOT') ? 'snapshot' : version
}
